import { useState } from 'react';
import { Document, Page, Text, View, Image, StyleSheet, pdf } from '@react-pdf/renderer';
import QRCode from 'qrcode';
import { toast } from 'sonner';
import { Download, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { supabase } from '../../lib/supabase';
import { formatMoney } from './finance-api';

export interface ReceiptCore {
  institution: { name: string; address?: string | null; contact?: string | null; logoUrl?: string | null };
  receiptNo: string;
  date: string;            // ISO
  student: { name: string; admissionNumber: string };
  invoice: { reference: string; title: string; balance: number };
  amount: number;
  method: string;
  currency: string;
}
export interface ReceiptData extends ReceiptCore { verifyUrl: string; qrDataUrl: string; }

const s = StyleSheet.create({
  page: { padding: 26, fontSize: 10, color: '#0f172a', fontFamily: 'Helvetica' },
  headerRow: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 2, borderBottomColor: '#0f172a', paddingBottom: 8, marginBottom: 10 },
  logo: { width: 42, height: 42, objectFit: 'contain', marginRight: 10 },
  instName: { fontSize: 14, fontFamily: 'Helvetica-Bold' },
  instMeta: { fontSize: 8, color: '#475569', marginTop: 2 },
  titleRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  title: { fontSize: 12, fontFamily: 'Helvetica-Bold', letterSpacing: 1 },
  meta: { fontSize: 9, color: '#475569', textAlign: 'right' },
  row: { flexDirection: 'row', marginBottom: 4 },
  label: { width: 110, color: '#64748b' },
  value: { flex: 1 },
  amountBox: { marginTop: 10, borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 4, padding: 10, backgroundColor: '#f8fafc' },
  amount: { fontSize: 18, fontFamily: 'Helvetica-Bold' },
  footer: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 22 },
  qr: { width: 58, height: 58 },
  verifyText: { fontSize: 7, color: '#64748b', maxWidth: 300 },
});

function Receipt({ data }: { data: ReceiptData }) {
  const i = data.institution;
  return (
    <Document>
      <Page size="A5" style={s.page}>
        <View style={s.headerRow}>
          {i.logoUrl ? <Image src={i.logoUrl} style={s.logo} /> : null}
          <View style={{ flex: 1 }}>
            <Text style={s.instName}>{i.name}</Text>
            {i.address ? <Text style={s.instMeta}>{i.address}</Text> : null}
            {i.contact ? <Text style={s.instMeta}>{i.contact}</Text> : null}
          </View>
        </View>

        <View style={s.titleRow}>
          <Text style={s.title}>PAYMENT RECEIPT</Text>
          <View>
            <Text style={s.meta}>No: {data.receiptNo}</Text>
            <Text style={s.meta}>{new Date(data.date).toLocaleDateString()}</Text>
          </View>
        </View>

        <View style={s.row}><Text style={s.label}>Received from</Text><Text style={s.value}>{data.student.name} ({data.student.admissionNumber})</Text></View>
        <View style={s.row}><Text style={s.label}>For</Text><Text style={s.value}>{data.invoice.title} · {data.invoice.reference}</Text></View>
        <View style={s.row}><Text style={s.label}>Method</Text><Text style={s.value}>{data.method}</Text></View>

        <View style={s.amountBox}>
          <Text style={{ color: '#64748b', fontSize: 8 }}>Amount paid</Text>
          <Text style={s.amount}>{formatMoney(data.amount, data.currency)}</Text>
          <Text style={{ color: '#64748b', fontSize: 8, marginTop: 4 }}>Outstanding balance: {formatMoney(data.invoice.balance, data.currency)}</Text>
        </View>

        <View style={s.footer}>
          <Text style={s.verifyText}>Verify at {data.verifyUrl}. Computer-generated receipt, valid with the QR code. Generated by NegoLinks Education ERP.</Text>
          <Image src={data.qrDataUrl} style={s.qr} />
        </View>
      </Page>
    </Document>
  );
}

export async function generateReceiptBlob(data: ReceiptData): Promise<Blob> {
  return pdf(<Receipt data={data} />).toBlob();
}

export function ReceiptButton({ paymentId, assemble, label = 'Receipt' }: {
  paymentId: string; assemble: () => ReceiptCore; label?: string;
}) {
  const [busy, setBusy] = useState(false);
  const onClick = async () => {
    try {
      setBusy(true);
      const { data: token, error } = await supabase.rpc('get_receipt_token', { _payment: paymentId });
      if (error) throw error;
      const verifyUrl = `${window.location.origin}/verify/${token}`;
      const qrDataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 140 });
      const blob = await generateReceiptBlob({ ...assemble(), verifyUrl, qrDataUrl });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `receipt-${assemble().receiptNo}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setBusy(false);
    }
  };
  return (
    <Button size="sm" variant="outline" onClick={onClick} disabled={busy}>
      {busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}{label}
    </Button>
  );
}
